### ISSUE TITLE
Application confusion

### ISSUE THREAD

**Issue by 32nguyen** [ucl-exoplanets/ExoGAN_public#1]
THanks

**Comment by tiziano1590** [comment]
Hi,

The uniform distribution in the inpainting section has been used to generate only the starting z_hat array. Since the input spectrum has its own error bars, we vary it within one sigma error bar, creating a batch of spectra. Each of the spectra, represent the same input spectrum and, given the amplitude of the error bar, they can converge to slightly different z_hats when inpainting is applied. 

Then we use Adam algorithm on the z_hats to converge to the optimal solution. The optimal z_hats will minimize the L=L_{conceptual}+\lambda*L_{perceptual} loss (as defined in Amos B. 2016). 

About the mask, currently it is possible to apply the hubble/wfc3 mask which covers the wavelength range between 1.1um and 1.7um and the "parameters", which leaves the whole available wavelength range between 0.3um and 15um. Given the mask, both the conceptual and perceptual loss are minimized in the inpainting algorithm. The masks are hard-coded in the model.py file and can be modified to adapt on other instruments.

The aim of Exogan is to find the optimal set of physical parameters associated to an input spectrum. Given an input spectrum, with inpainting we can eventually reconstruct his components between 0.3um and 15um together with his physical parameters. These parameters are described in blocks 6-12 of the ASPA (see Fig 3 of Exogan paper https://arxiv.org/pdf/1806.02906.pdf).

I hope I have clarified your doubts.

Best,
Tiziano

**Comment by tiziano1590** [comment]
I will close this issue now. Feel free to reopen it anytime if you need it!

**Comment by 32nguyen** [comment]
@Tiziano 
Hi, 

Thank you for your detailed answer. I had some searching for in-painting with GAN and understanding better your implementation. 


Bests,

Thanh
